site_name: Calcium imaging analysis tool (based on LUMIN)
site_url: https://lisadvn.github.io/Lumin_custom/

theme:
  name: material
  logo: 
  favicon: 

  features:
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: 
    - Workflow Overview: workflow.md
    - Installation: installation.md

  - Pipeline Modules:
    - 1. Data input & metadata: input.md
    - 2. Segmentation & signal extraction: segmentation.md
    - 3. Event detection: eventdetection.md
    - 4. Spike detection: spikedetection.md
    - Parameters: parameter.md
    - Features: features.md
  - GUI Usage: gui.md
  - FAIR Principles: fair.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  homepage: index.md

plugins:
  - search
  - mkdocs-video

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - docs