[metadata]
name = LUMIN
version = 0.0.1
classifiers =
    Framework :: napari

#[options]
#packages = find:
##include_package_data = True
#i#nstall_requires =
#    napari

[options.entry_points]
console_scripts =
    lumin = lumin._launcher:main
    lumin-install-shortcut = create_shortcut:create_shortcut
    
[options]
packages = find:
include_package_data = True
python_requires = >=3.7
install_requires =
    stardist==0.9.2
    tensorflow==2.10.1; platform_system!="Darwin" or platform_machine!="arm64"
    tensorflow-macos; platform_system=="Darwin" and platform_machine=="arm64"
    tensorflow-metal; platform_system=="Darwin" and platform_machine=="arm64"
    napari[all]==0.6.6
    cellpose==3.1.1.1
    numpy==1.24.2; platform_system!="Darwin" or platform_machine!="arm64"
    numpy<2.0.0; platform_system=="Darwin" and platform_machine=="arm64"
    pandas
    magicgui==0.10.1
    scikit-image
    scikit-learn
    scipy
    matplotlib
    seaborn
    natsort
    opencv-python-headless
    napari-blob-detection==0.0.2
    pca
    csbdeep
    notebook
    ipykernel
    PyQt5==5.15.11
    pyshortcuts